#!/usr/bin/env bash
# dsh21-deploy.sh — install the zero-download headless profile on a remote dsh host.
#
# The dsh web UI needs ~3.34 MB of plugin bundles before it is usable, which is why
# it is unusable on a 25 KB/s VPN. `dsh --profile headless` needs none of that, but
# the remote has to have the profile. It is 173 bytes: the headless bundle declares
# NO dependencies and reuses the dsh-base/dsh-headless packages already installed in
# the shared $DSH_HOME/profiles/node_modules.
#
# This script refuses to proceed if those packages are missing, because the fix
# would then require a download. It never runs pnpm and never installs anything.
#
# Usage: scripts/dsh21-deploy.sh [host]      (default host: dgx21.tun)
set -euo pipefail

host="${1:-dgx21.tun}"

# Non-interactive ssh does not source ~/.bashrc, and dsh is usually NOT on the
# default PATH. Cover the layouts seen in practice: ~/.local/node/bin (dgx21) and
# ~/.nvm/versions/node/<ver>/bin (c4g.tun, where dsh lives under v24.15.0).
#
# The nvm entry MUST be a for-loop word list, not a plain assignment: assignments
# do not undergo pathname expansion, so `export PATH=.../node/*/bin` would leave a
# literal star in PATH and quietly match nothing. Same pattern as src/control/remote.js.
#
# The leading zsh guard is not decoration: zsh's default `nomatch` makes an
# unmatched glob FATAL for the whole command line, so on a zsh host (cms.tun) the
# loop would abort everything after it -- including the `dsh` call itself.
remote() {
  ssh -o BatchMode=yes -o ConnectTimeout=20 -o ClearAllForwardings=yes \
      -o ServerAliveInterval=15 -o ServerAliveCountMax=4 \
      -- "$host" '[ -n "${ZSH_VERSION:-}" ] && unsetopt nomatch 2>/dev/null; \
                for d in "$HOME/.nvm/versions/node/"*/bin "$HOME/.npm-global/bin" \
                  "$HOME/.local/bin" "$HOME/.local/node/bin" "$HOME/bin" "/usr/local/bin"; do \
                  [ -d "$d" ] || continue; \
                  case ":$PATH:" in *":$d:"*) ;; *) PATH="$d:$PATH";; esac; done; \
                export PATH; '"$1"
}

echo "host: $host"

# --- preflight: the packages this profile reuses must already be there -------------
if ! remote 'test -d "$HOME/.dsh/profiles/node_modules/@deepseek-ai/dsh-base" \
          && test -d "$HOME/.dsh/profiles/node_modules/@deepseek-ai/dsh-headless"'; then
  echo "ERROR: dsh-base / dsh-headless missing under \$HOME/.dsh/profiles/node_modules" >&2
  echo "       Installing them would mean a download, which this route exists to avoid." >&2
  echo "       Run dsh once on that host (any profile) so its own deps are in place." >&2
  exit 3
fi
echo "preflight: dsh-base + dsh-headless present (no download will be needed)"

if ! remote 'command -v dsh >/dev/null 2>&1'; then
  echo "ERROR: dsh not found on the remote PATH." >&2
  echo "       searched: ~/.nvm/versions/node/<ver>/bin ~/.npm-global/bin ~/.local/bin ~/.local/node/bin ~/bin /usr/local/bin" >&2
  exit 3
fi

# --- write the 173-byte profile ---------------------------------------------------
read -r -d '' pkg <<'JSON' || true
{"name":"dsh-profile-headless","private":true,"dependencies":{},"dsh":{"profile":{"bundles":["@deepseek-ai/dsh-base","@deepseek-ai/dsh-headless"],"patchReload":"startup"}}}
JSON

# '--' before the host: ssh would otherwise read a leading-dash host as its own option.
printf '%s\n' "$pkg" | ssh -o BatchMode=yes -o ConnectTimeout=20 -o ClearAllForwardings=yes \
  -- "$host" 'mkdir -p "$HOME/.dsh/profiles/headless" && cat > "$HOME/.dsh/profiles/headless/package.json"'
echo "wrote: \$HOME/.dsh/profiles/headless/package.json $(remote 'wc -c < "$HOME/.dsh/profiles/headless/package.json"' | tr -d ' ') bytes"
echo "note:  cordis.yml is generated by dsh itself on first boot (no action needed)"

# --- verify it actually boots -----------------------------------------------------
if remote 'dsh --profile headless --help >/dev/null 2>&1'; then
  echo "verify: dsh --profile headless boots OK"
else
  echo "ERROR: the profile was written but does not boot. Check: dsh --profile headless --help" >&2
  exit 1
fi

cat <<EOF

done. Send an instruction with:
  node scripts/dsh21.mjs --host $host "your instruction"
or directly:
  ssh $host 'export PATH=\$HOME/.local/node/bin:\$PATH; dsh --profile headless "your instruction"'
EOF
